import type { CharacterId } from "../config";

export const strings = {
  title: "לוחם ישיבה",
  tagline: "למה שלוחם תורה יהיה פחות מלוחם קרבי?",
  start: "התחל משחק",
  muteOn: "צליל כבוי",
  muteOff: "צליל פועל",
  selectTitle: "בחר את הלוחם שלך",
  choose: "בחר",
  continue: "המשך",
  playAgain: "שחק שוב",
  backToMenu: "חזרה לתפריט",
  scoreLabel: "נקודות",
  stageLabel: (n: number) => `שלב ${n}`,
  gameTitleHud: "לוחם ישיבה",
  recruit: "גיוס לוחם תורה",
  hit: "הותר לפירסום: לוחם תורה נכנס לכלא.",
  pickupInvincible: "קיבלת פטור ממכשולים",
  pickupFreeze: "המציאות הוקפאה",
  freezeOn: "המכשולים הוקפאו!",
  freezeOff: "ההקפאה הסתיימה",
  invincibleTimer: (n: number) => `חסינות: ${n}`,
  freezeTimer: (n: number) => `הקפאה: ${n}`,
  stageCompleteTitle: "הצלחה!",
  stageCompleteBody: "לוחם נוסף הגיע לישיבת כספי קודש.",
  plusOne: "+1 נקודה",
  gameOver: "GAME OVER",
  gameOverBody: "הלוחם נפסל.",
  contributionStopped: "התרומה הופסקה זמנית.",
  tryAgain: "נסה שוב.",
  reachedYeshivas: (n: number) => `הגעת ל־${n} ישיבות`,
  victoryTitle: "אסון!",
  victoryBody: "לא הצלחנו להשלים את מהפיכת הדת.",
  victoryDone: "ועוד יותר גרוע - גם תצטרך ללכת לעבוד.",
  stagesDone: "שלבים שהושלמו: 4",
  failSuccess: "שלומפר, הצלחת להיכשל.",
  failSuccessAlt: "נכשלת!",
  missionComplete: "",
  failPointReached: "יש גבול לניצול.",
  character: "לוחם",
  livesLeft: "חיים שנותרו",
  characterNames: {
    torah: "לוחם תורה",
    tefillin: "לוחם תפילין",
    yeshiva: "לוחם ישיבה",
  } satisfies Record<CharacterId, string>,
  characterBlurb: {
    torah: "ספר ביד. תנוחה גיבורית.",
    tefillin: "תיק תפילין. ברק קטן.",
    yeshiva: "תיק ישיבה. מראה קרבי.",
  } satisfies Record<CharacterId, string>,
  intros: {
    1: {
      title: "שלב 1",
      body: "צריך להשלים מניין.\nאבל גלי בהרב מיארה רוצה לתפוס את לווחמי התורה.",
    },
    2: {
      title: "שלב 2",
      body: "גלי ממשיכה להקשות אבל יש עזרה מלמעלה.",
    },
    3: {
      title: "שלב 3",
      body: "הגלים מתחזקים. עזרה מלמעלה תרויח לך עוד זמן.",
    },
    4: {
      title: "שלב 4",
      body: "עוד מאמץ קטן ויהיה מניין להשלים את מהפיכת הדת.",
    },
  },
} as const;
